heap: heap.o 
	gcc -o heap heap.o -lm
	./heap

heap.o: heap.c
	gcc -c heap.c -lm

priorities: priorities.o 
	gcc -o priorities priorities.o
	./priorities

priorities.o: priorities.c
	gcc -c priorities.c

clean:
	rm -f *.o
	rm -f *.o
